# General
title: Brandon Dorn
email: brandon.s.dorn@gmail.com
description: A designer who thinks with his heart and acts with his mind.
url: "http://brandorn.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Other
permalink: /:title