# General
title: Brandon Dorn
email: brandon.s.dorn@gmail.com
description: A designer who thinks with his heart and acts with his mind.
url: "http://brandorn.com" # the base hostname & protocol 

# Build settings
markdown: kramdown

# Other
permalink: /:categories/:title
sass:
  sass_dir: src/styles/_sass